apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  namespace: laboratory-swarm
spec:
  replicas: 10
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
        - name: drone
          image: localhost:5000/drone:latest  # Zastąp odpowiednim rejestrem, jeśli to konieczne
          env:
            - name: DRONE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MQTT_BROKER
              value: "mqtt-broker.laboratory-swarm.svc.cluster.local"
            - name: MQTT_PORT
              value: "1883"
            - name: AGGREGATOR_HOST
              value: "aggregator-service.laboratory-swarm.svc.cluster.local"
            - name: AGGREGATOR_PORT
              value: "6000"
          ports:
            - containerPort: 7000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
