apiVersion: v1
kind: Service
metadata:
  name: drone-service
  namespace: laboratory-swarm
spec:
  selector:
    app: drone
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name: drone
  type: ClusterIP
