apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  labels:
    app: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: localhost:5000/ai-service:latest
          ports:
            - containerPort: 9000
          env:
            - name: MODEL_PATH
              value: "/app/model.joblib"
