apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  type: ClusterIP
