apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: serwer-alerts
  namespace: laboratory-swarm
spec:
  groups:
    - name: serwer-alerts
      rules:
        - alert: SerwerHighErrorRate
          expr: rate(http_requests_total{response_code=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Wysoki wskaźnik błędów serwera"
            description: "Serwer {{ $labels.app }} ma więcej niż 5% błędów 5xx przez ostatnie 2 minuty."
        - alert: SerwerHighLatency
          expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Wysoka latencja na serwerze"
            description: "99. percentyl latencji przekracza 1 sekundę przez ostatnie 2 minuty."
