apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-aggregator
  template:
    metadata:
      labels:
        app: mqtt-aggregator
    spec:
      containers:
        - name: mqtt-aggregator
          image: localhost:5000/mqtt-aggregator:latest
          env:
            - name: MQTT_BROKER
              value: "mqtt-broker"
            - name: MQTT_PORT
              value: "1883"
