apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-swarm
spec:
  replicas: 5
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
        - name: drone
          image: localhost:5000/mydrone:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DRONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGGREGATOR_HOST
              value: "aggregator-service"  # Adres agregatora
            - name: AGGREGATOR_PORT
              value: "5001"
          ports:
            - containerPort: 5000
