apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: laboratory-swarm
type: Opaque
data:
  POSTGRES_USER: ZGF0YWJhc2VfYWRtaW4= # base64 dla 'database_admin'
  POSTGRES_PASSWORD: SmEzXkhTNCRRc2tuUzI= # base64 dla 'Ja3^HS4$QsknS2'
  POSTGRES_DB_URL: cG9zdGdyZXNxbDovL2RhdGFiYXNlX2FkbWluOkphM15IUzQkUXNrblMyQHBvc3RncmVzcWwubGFib3JhdG9yeS1zd2FybS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2Ryb25lX2Ri # base64 dla 'postgresql://database_admin:Ja3^HS4$QsknS2@postgresql.laboratory-swarm.svc.cluster.local:5432/drone_db'
