apiVersion: v1
kind: Service
metadata:
  name: aggregator-api-service
  namespace: laboratory-swarm
spec:
  selector:
    app: aggregator-api
  ports:
    - name: http
      port: 6001
      targetPort: 6001
      protocol: TCP
  type: ClusterIP
