apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-api
  namespace: laboratory-swarm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregator-api
  template:
    metadata:
      labels:
        app: aggregator-api
    spec:
      containers:
        - name: aggregator-api
          image: localhost:5000/aggregator-api:latest  # Zastąp odpowiednim rejestrem, jeśli to konieczne
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgresql.laboratory-swarm.svc.cluster.local:5432/drone_db"
          ports:
            - containerPort: 6001
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
