apiVersion: v1
kind: Service
metadata:
  name: kubediag-service
  labels:
    app: kubediag
spec:
  selector:
    app: kubediag
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
