apiVersion: v1
kind: ServiceAccount
metadata:
  name: aggregator-serviceaccount
  namespace: laboratory-swarm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: laboratory-swarm
  name: aggregator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aggregator-rolebinding
  namespace: laboratory-swarm
subjects:
  - kind: ServiceAccount
    name: aggregator-serviceaccount
    namespace: laboratory-swarm
roleRef:
  kind: Role
  name: aggregator-role
  apiGroup: rbac.authorization.k8s.io
