apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  namespace: laboratory-swarm
spec:
  selector:
    app: aggregator
  ports:
    - name: aggregator-udp
      port: 6000
      targetPort: 6000
      protocol: UDP
  type: ClusterIP
