apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - name: aggregator
          image: localhost:5000/aggregator:latest
          ports:
            - containerPort: 5001
          env:
            - name: AGGREGATOR_PORT
              value: "5001"
