apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
spec:
  selector:
    app: aggregator
  ports:
    - name: aggregator-udp
      port: 5001
      targetPort: 5001
      protocol: UDP
  type: ClusterIP
