apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  namespace: laboratory-swarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - name: aggregator
          image: localhost:5000/aggregator:latest  # Zastąp odpowiednim rejestrem, jeśli to konieczne
          ports:
            - containerPort: 6000
              protocol: UDP
          env:
            - name: AGGREGATOR_PORT
              value: "6000"
            - name: AGGREGATOR_API_URL
              value: "http://aggregator-api-service.laboratory-swarm.svc.cluster.local:6001/api/data"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
