apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      # Jeśli chcesz poczekać na dostępność innych usług,
      # możesz dodać initContainers - np. czekanie na aggregator
      # initContainers:
      #   - name: wait-for-something
      #     image: nicolaka/netshoot
      #     command: ["sh", "-c", "until nc -z aggregator-service 5001; do echo waiting; sleep 2; done"]
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-config
            # klucz 'mosquitto.conf' zostanie zamapowany na plik w /mosquitto/config
      containers:
        - name: mqtt-broker
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config
