apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: laboratory-swarm
spec:
  selector:
    app: mqtt-broker
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  type: ClusterIP
