apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-bridge
  template:
    metadata:
      labels:
        app: mqtt-bridge
    spec:
      initContainers:
        - name: wait-for-mqtt
          image: nicolaka/netshoot
          command: ["sh", "-c", "until nc -z mqtt-broker 1883; do echo waiting for mqtt-broker; sleep 2; done"]

      containers:
      - name: mqtt-bridge
        # Obraz zbudowany na bazie Dockerfile w katalogu mqtt_bridge/
        # Zmieniaj zgodnie z rejestrem/kontrolerem obrazów
        image: localhost:5000/mqtt-bridge:latest
        env:
          - name: MQTT_BROKER
            value: "mqtt-broker"
          - name: MQTT_PORT
            value: "1883"
          # Domyślnie mqtt_bridge.py używa MQTT_TOPIC=drone/positions,
          # ale można to nadpisać, np.:
          # - name: MQTT_TOPIC
          #   value: "some/other/topic"

        # Można dodać ograniczenia zasobów i zapotrzebowania, np.:
        # resources:
        #   requests:
        #     cpu: "50m"
        #     memory: "64Mi"
        #   limits:
        #     cpu: "200m"
        #     memory: "128Mi"
