apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-bridge
  namespace: laboratory-swarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-bridge
  template:
    metadata:
      labels:
        app: mqtt-bridge
    spec:
      initContainers:
        - name: wait-for-mqtt
          image: nicolaka/netshoot
          command: ["sh", "-c", "until nc -z mqtt-broker 1883; do echo waiting for mqtt-broker; sleep 2; done"]
      containers:
        - name: mqtt-bridge
          image: localhost:5000/mqtt-bridge:latest
          env:
            - name: MQTT_BROKER
              value: "mqtt-broker.laboratory-swarm.svc.cluster.local"
            - name: MQTT_PORT
              value: "1883"
            - name: TARGET_API_URL
              value: "http://aggregator-api-service.laboratory-swarm.svc.cluster.local:6001/api/data"
            - name: MQTT_TOPIC
              value: "drone/positions"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
